# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'AmHere' do

pod 'JSQMessagesViewController' 

end

target 'AmHereTests' do

end

platform :ios , 7.0 
pod 'ProtocolBuffers', '1.9.2'
